-- Dev/demo seed data.
--
-- NOTE: no seeded user accounts. Password hashes must be generated by the
-- application's own BCryptPasswordEncoder to be valid, so hardcoding one here
-- is error-prone. Register through the UI instead (POST /api/auth/register),
-- then promote to admin if needed:
--
--   UPDATE users SET role='ADMIN' WHERE email='<your email>';

INSERT INTO products (title, description, image_url, base_price) VALUES
  ('Aurora Wireless Earbuds', 'Noise-cancelling earbuds, 30h battery.', 'https://picsum.photos/seed/aurora/480/320', 4999.00),
  ('Pulse Smartwatch Pro', 'AMOLED display, 7-day battery, SpO2.', 'https://picsum.photos/seed/pulse/480/320', 8999.00);

INSERT INTO sale_events (product_id, sale_price, total_stock, sold_count, per_user_limit, starts_at, ends_at, status) VALUES
  (1, 2999.00, 100, 0, 1, now() - interval '1 minute', now() + interval '2 hours', 'LIVE'),
  (2, 5999.00, 50,  0, 1, now() + interval '1 day', now() + interval '1 day 2 hours', 'SCHEDULED');
